[package]
name = "imgui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.60.1"
regex = "1.5.6"
lazy_static = "1.4.0"

[dependencies]
bitflags = "1.3.2"