[package]
name = "aetherment"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aetherment_core"
crate-type = ["dylib"]

# i'm too dumb to figure out how to get the device on rust side
# [dependencies.windows]
# version = "0.37.0"
# features = [
# 	"Win32_Graphics_Direct3D11",
# 	"Win32_Foundation",
# 	"Win32_Graphics_Direct3D",
# 	"Win32_Graphics_Dxgi",
# 	"Win32_Graphics_Dxgi_Common",
# ]

[dependencies]
anyhow = {version = "1.0.57"}
rayon = "1.5.3"
walkdir = "2.3.2"
path-slash = "0.1.4"
blake3 = "1.3.1"
flate2 = "1.0.23"
brotli = "3.3.4"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0"
lazy_static = "1.4.0"
image = "0.24.2"
reqwest = {version = "0.11.10", features = ["blocking", "json", "multipart"]}
noumenon = {path = "../noumenon"}
ironworks = {git = "https://github.com/ackwell/ironworks", rev = "bd787883d324f3a150bce5f1ab348d86e770e23e", features = ["ffxiv", "sqpack"]}